name: Realme Trinket Kernel Build Clang18

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

    - name: Checkout Kernel Source
      uses: actions/checkout@v4


    - name: Install Dependencies
      run: |
        sudo apt update

        sudo apt install -y \
          bc \
          bison \
          flex \
          build-essential \
          libssl-dev \
          libelf-dev \
          dwarves \
          python3 \
          wget \
          xz-utils \
          gcc-aarch64-linux-gnu


    - name: Install Clang LLVM 18
      run: |

        wget -q \
        https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/clang+llvm-18.1.8-x86_64-linux-gnu-ubuntu-22.04.tar.xz

        tar -xf clang+llvm-18.1.8-x86_64-linux-gnu-ubuntu-22.04.tar.xz

        mv \
        clang+llvm-18.1.8-x86_64-linux-gnu-ubuntu-22.04 \
        llvm18

        echo "$PWD/llvm18/bin" >> $GITHUB_PATH

        clang --version
        ld.lld --version


    - name: Prepare Build Directory
      run: |
        mkdir -p out


    - name: Load Trinket Defconfig
      run: |

        if [ -f arch/arm64/configs/vendor/trinket_defconfig ]; then

          cp arch/arm64/configs/vendor/trinket_defconfig out/.config

        else

          cp arch/arm64/configs/trinket_defconfig out/.config

        fi


        make \
        O=out \
        ARCH=arm64 \
        olddefconfig


    - name: Kernel Config Fix
      run: |

        scripts/config --file out/.config \
        -d CONFIG_WERROR


        scripts/config --file out/.config \
        -e CONFIG_MODULES \
        -e CONFIG_MODULE_UNLOAD \
        -e CONFIG_MODULE_FORCE_LOAD \
        -e CONFIG_MODULE_FORCE_UNLOAD


        scripts/config --file out/.config \
        -d CONFIG_MODULE_SIG \
        -d CONFIG_MODULE_SIG_FORCE


        make \
        O=out \
        ARCH=arm64 \
        olddefconfig


    - name: Build Kernel
      run: |

        set -o pipefail


        make \
        O=out \
        ARCH=arm64 \
        CC=clang \
        LLVM=1 \
        LLVM_IAS=1 \
        CROSS_COMPILE=aarch64-linux-gnu- \
        KCFLAGS="-Wno-error" \
        -j$(nproc) 2>&1 | tee build.log


    - name: Show Errors If Failed
      if: failure()
      run: |

        echo "========== ERRORS =========="

        grep -iE \
        "error:|fatal:|modpost|ld.lld|undefined" \
        build.log || true


    - name: Check Kernel Output
      run: |

        echo "========== OUTPUT =========="

        ls -lh out/vmlinux || true

        ls -lh out/arch/arm64/boot/Image || true


    - name: Upload Build Log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: build.log


    - name: Upload Kernel Image
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: realme-trinket-kernel-clang18
        path: |
          out/vmlinux
          out/arch/arm64/boot/Image
