name: Realme 5i Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Kernel Source
      uses: actions/checkout@v4
      with:
        clean: false
        fetch-depth: 1


    - name: Install Dependencies
      run: |
        sudo apt update

        sudo apt install -y \
          bc \
          bison \
          flex \
          build-essential \
          libssl-dev \
          libelf-dev \
          python3 \
          python-is-python3 \
          cpio \
          rsync \
          clang-18 \
          llvm-18 \
          lld-18 \
          gcc-aarch64-linux-gnu \
          binutils-aarch64-linux-gnu \
          device-tree-compiler


    - name: Toolchain Check
      run: |
        clang-18 --version
        ld.lld-18 --version
        aarch64-linux-gnu-gcc --version


    - name: Create Output Directory
      run: |
        rm -rf out
        mkdir -p out


    - name: Setup Realme 5i Defconfig
      run: |

        echo "Available trinket configs:"
        find arch/arm64/configs -name "*trinket*"


        DEFCONFIG="vendor/trinket_oppo/trinket_defconfig"


        if [ ! -f "arch/arm64/configs/$DEFCONFIG" ]; then
          echo "Defconfig not found!"
          exit 1
        fi


        echo "Using defconfig:"
        echo $DEFCONFIG


        export PATH=/usr/lib/llvm-18/bin:$PATH


        make O=out \
          ARCH=arm64 \
          LLVM=1 \
          LLVM_IAS=1 \
          CROSS_COMPILE=aarch64-linux-gnu- \
          $DEFCONFIG



    - name: Fix Clang 18 ARM64 Issue
      run: |

        FILE="arch/arm64/include/asm/stack_pointer.h"

        if [ -f "$FILE" ]; then

          sed -i \
          's/register unsigned long current_stack_pointer asm ("sp");/static inline unsigned long current_stack_pointer(void) { unsigned long sp; asm("mov %0, sp" : "=r"(sp)); return sp; }/' \
          $FILE || true

        fi



    - name: Build Kernel
      run: |

        export PATH=/usr/lib/llvm-18/bin:$PATH

        set -o pipefail


        make -j$(nproc) \
          O=out \
          ARCH=arm64 \
          LLVM=1 \
          LLVM_IAS=1 \
          CROSS_COMPILE=aarch64-linux-gnu- \
          KCFLAGS="-Wno-error -Wno-array-bounds" \
          2>&1 | tee build.log



    - name: Check Kernel Image
      if: always()
      run: |

        echo "Checking kernel output..."

        ls -lh out/arch/arm64/boot/ || true


        if [ -f out/arch/arm64/boot/Image.gz ]; then
          echo "Image.gz FOUND"

        elif [ -f out/arch/arm64/boot/Image ]; then
          echo "Image FOUND"

        else
          echo "Kernel Image missing"
          tail -100 build.log
          exit 1
        fi



    - name: Upload Kernel
      if: always()
      uses: actions/upload-artifact@v4

      with:

        name: Realme5i-Kernel

        path: |
          out/arch/arm64/boot/*
          out/.config
          build.log

        if-no-files-found: warn
